language: node_js
node_js: '10'
sudo: required
# branches:
#   only:
#     - develop
#     - master
#     - /^(?i:release|hotfix).*$/
services:
  - docker
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - SC_DEMO_USER_PASSWORD=schulcloud
    - BACKEND_URL=https://api.schul-cloud.org
    - PUBLIC_BACKEND_URL=https://api.schul-cloud.org
    - FEATURE_TEAMS_ENABLED=true
    - IT_CLIENT_HOST=client
    - BRANCH_NAME=${TRAVIS_PULL_REQUEST_BRANCH:=$TRAVIS_BRANCH}
before_install:
  - openssl aes-256-cbc -K $encrypted_839866e404c6_key -iv $encrypted_839866e404c6_iv -in travis_rsa.enc -out travis_rsa -d
  - echo $BRANCH_NAME
  # move client into subdirectory
  - mkdir -p schulcloud-client
  - mv !(schulcloud-client) schulcloud-client
  # clone other required repositories and try to switch to branch with same name as current one
  - git clone https://github.com/schul-cloud/schulcloud-server.git schulcloud-server
  - sh ./schulcloud-client/test/switch_branch.sh "schulcloud-server" $BRANCH_NAME
  - git clone https://github.com/schul-cloud/docker-compose.git docker-compose
  - sh ./schulcloud-client/test/switch_branch.sh "docker-compose" $BRANCH_NAME
  - git clone https://github.com/schul-cloud/integration-tests.git integration-tests
  - sh ./schulcloud-client/test/switch_branch.sh "integration-tests" $BRANCH_NAME
install:
  # client packages are needed for mocha
  - cd schulcloud-client && npm ci && cd ..
  # dependencies for integration tests
  - docker-compose -f docker-compose/docker-compose.integration-test-Build.yml up -d
  - cd integration-tests && npm ci && cd ..
  - cd schulcloud-server && npm run setup && cd .. # initially seed database
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - cd schulcloud-client && npm run mocha && cd ..
  - cd integration-tests && npm run all && cd ..
# cache:
#   directories:
#     - schulcloud-client/node_modules
#     - integration-tests/node_modules
# deploy:
#   provider: script
#   script: bash ./deploy.sh
#   on:
#     all_branches: true
#     # condition: "$TRAVIS_BRANCH =~ ^master|N21/merge$"
