language: node_js
node_js: '10'
sudo: required
branches:
  only:
    - develop
    - master
    - /^(?i:release|hotfix).*$/
services:
  - docker
env:
  global:
    - GIT_SHA=$( git rev-parse HEAD )
    - SC_DEMO_USER_PASSWORD=Schulcloud1!
    - BACKEND_URL=http://localhost:3030
    - PUBLIC_BACKEND_URL=http://localhost:3030
    - FEATURE_TEAMS_ENABLED=true
    - IT_CLIENT_HOST=client
    - BRANCH_NAME=${TRAVIS_PULL_REQUEST_BRANCH:=$TRAVIS_BRANCH}

jobs:
  include:
    - stage: test
      name: Mocha
      script: npm run mocha
    - script:
        - curl https://gist.githubusercontent.com/schul-cloud-bot/a849c38804174f99ca7818782bf03c00/raw/index.sh > integration-test.sh
        - chmod 700 integration-test.sh
        - sh integration-test.sh
      name: "Integration"
      git:
        clone: false
      install:
        - echo "skipping install"
    - stage: deploy
      name: deploy
      before_install:
        - openssl aes-256-cbc -K $encrypted_839866e404c6_key -iv $encrypted_839866e404c6_iv -in travis_rsa.enc -out travis_rsa -d
      before_script:
        - echo $TRAVIS_BRANCH
        - echo $TRAVIS_TAG
      script:
        - bash ./schulcloud-client/deploy.sh

cache:
  directories:
    - "$HOME/.npm" # cache all packages installed with "npm ci"
