language: node_js
node_js: '10'
sudo: required
services:
- docker
git:
  clone: false
env:
  global:
  - GIT_SHA=$( git rev-parse HEAD )
  - SC_DEMO_USER_PASSWORD=schulcloud
  - BACKEND_URL=https://api.schul-cloud.org
  - PUBLIC_BACKEND_URL=https://api.schul-cloud.org
  - FEATURE_TEAMS_ENABLED=true
addons:
  chrome: stable
  firefox: latest
before_install:
  # clone integration tests into `tests` directory
  - git clone https://github.com/schul-cloud/schulcloud-client.git schulcloud-client
  - git clone https://github.com/schul-cloud/schulcloud-server.git schulcloud-server
  - git clone https://github.com/schul-cloud/docker-compose.git docker-compose
  - cd docker-compose && docker-compose -f docker-compose.integration-test.yml up -d && cd ..
  - git clone https://github.com/schul-cloud/integration-tests.git integration-tests
  - cd integration-tests
  - npm ci
  - npm install selenium-standalone@latest -g
  - selenium-standalone install
  - selenium-standalone start &
  - sleep 5
script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - cd integration-tests && node index.js -d -t @teacherLogin
after_success:
  - bash ./deploy.sh
