version: '3'

services:

  schulcloud-client:
    image: schulcloud-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://server:3030/
      # Theme and Titles
      - SC_THEME=default
      - SC_TITLE=TSC
      - SC_SHORT_TITLE=TSC
      - SC_PRODUCTNAME=TSC
    ports:
      - 3100:3100
      - 9310:9310
    networks:
      - default
      - schulcloud-server_client-net
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: npm run debug:container

networks:
  schulcloud-server_client-net:
    external: true